### ISSUE TITLE
Gitcoin Grants GR19 Submission

### ISSUE THREAD

**Issue by burningtree** [web3privacy/pm#2]
![Image](https://github.com/web3privacy/w3pn-core/assets/67269/a5b7ecca-0115-47fd-9f61-f8505871b493)

https://explorer.gitcoin.co/#/round/424/0x98720dd1925d34a2453ebc1f91c9d48e7e89ec29

**Comment by EclecticSamurai** [comment]
https://builder.gitcoin.co/#/chains/424/registry/0xDF9BF58Aa1A1B73F0e214d79C652a7dd37a6074e/projects/361

**Comment by burningtree** [comment]
Why is it still not active for donations?
